sudo: required
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - boost-latest
          - sourceline: 'ppa:canonical-qt5-edgers/ubuntu1204-qt5'
          packages:
          - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
          - boost-latest
          - sourceline: 'ppa:canonical-qt5-edgers/ubuntu1204-qt5'
          packages:
          - clang-3.8
      env: COMPILER=clang++-3.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libev-dev libboost-filesystem1.55-dev qtbase5-dev

script:
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_CXX_FLAGS="-std=c++14" -DCMAKE_INSTALL_PREFIX=$HOME ..
  - make install
