sudo: required
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    - boost-latest
    - sourceline: 'ppa:canonical-qt5-edgers/ubuntu1204-qt5'
    packages:
    - g++-5
    - clang-3.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libev-dev libboost-filesystem1.55-dev qtbase5-dev
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_COMPILER=clang++-3.8 -DCMAKE_CXX_FLAGS="-std=c++14" -DCMAKE_INSTALL_PREFIX=$HOME ..
  - make

install:
  - make install
